### ISSUE TITLE
Can polydfe handle unfolded spectra?

### ISSUE THREAD

**Issue by jodyhey** [paula-tataru/polyDFE#10]
Can polydfe handle unfolded spectra?  Thanks for any info.

**Comment by paula-tataru** [comment]
Hi Jody

polyDFE unfolded spectra. This is because it infers fitness effects for both deleterious and beneficial mutations. From a folded spectra, only effects from deleterious mutations can be determined. polyDFE does not support that.

polyDFE is not actively being maintained anymore. If polyDFE is missing needed functionality, I suggest looking into fastDFE:
https://academic.oup.com/mbe/article/41/5/msae070/7641109
https://github.com/Sendrowski/fastDFE.
