### ISSUE TITLE
Expectation is SFS is negative

### ISSUE THREAD

**Issue by grillino** [paula-tataru/polyDFE#3]
Dear Paula,
thanks a lot for developing this fantastic software! 
I have a problem with the default parameters: if I try running polyDFE (from linux binary) on the example data set it produces the full output as it should. The command is simply:
./polyDFE-2.0-linux-64-bit -d input/example_2 > output/example_2_full_C

When I try the same command on my own data, the run ends in a second, the output file is basically empty (there are just a few comment lines starting with "----") and I get the following message in standard output:

Expectation is SFS is negative, i 49 n 98 S -3.90176e-05 hyper geo 0.999961 denom -0.0936794

Could you help me understand this issue? What does "negative SFS" mean? 
Thanks a lot in advance,
Andrea Fulgione

**Comment by paula-tataru** [comment]
Dear Andrea,

polyDFE has been thoroughly tested for a sample size 20. Feedback from users brought to light that the numerical calculations performed for the different expectations for the SFS are not very stable. Unfortunately for larger sample sizes that sometimes leads to negative estimations, as the error message says, but the expectation should be positive. I have to admit though that I am surprised you see that error, as I didn't expect it to happen for n = 98.

Unfortunately I have changed my job away from academia and I do not expect to have time to work on fixing this, even though I know what the fix should be...

Since you said that the output is basically empty, you might be able to circumvent the issue by using a different set of parameters as starting values (option -i, default is -e). Another option would be to use a different DFE model (option -m).

I hope this helps
Paula

**Comment by grillino** [comment]
Dear Paula,
thank you for the help. 
I subsampled my data set to a sample size near what you tested (20), which was the plan anyways to exclude low quality samples and now I do not get the error anymore. 
It is possible that I get this error with a sample size that you would expect to be fine because the population I work on has very low diversity and maybe this issue happens at lower sample sizes. I imagine it could have to do with zeroes in the spectrum...

Anyways my problem is solved, thanks a lot!
Andrea
