### ISSUE TITLE
Why bootstrap data has only one region?

### ISSUE THREAD

**Issue by AoyueBi** [paula-tataru/polyDFE#7]
Hello Tataru,
 I have four questions that make me confused:

**Question 1: Why bootstrap data has only one region?**
 I have made my input data "CL_A.txt" with 14  neutral regions and 14 selective regions in that file. When I run the function bootstrapData("~/CL_A.txt", rep = 10) using postprocessing.R, it gives me 10 input files. **But only one neutral region and one selective region. Why?**
 I am confused about the difference between the original input file and the bootstrap file. 
**Which one should I use to run polyDFE?**  
should I run the original CL_A.txt and the 10 bootstraps, total 11 files? 
or should I run the only 10 bootstraps input files?  Please see the attachment CL_A.txt CL_A.txt_01 CL_A.txt_02 ....
[CL_A.txt](https://github.com/paula-tataru/polyDFE/files/7496964/CL_A.txt)
[CL_A_01.txt](https://github.com/paula-tataru/polyDFE/files/7496969/CL_A_01.txt)
[CL_A_02.txt](https://github.com/paula-tataru/polyDFE/files/7496970/CL_A_02.txt)
[CL_A_03.txt](https://github.com/paula-tataru/polyDFE/files/7496973/CL_A_03.txt)

**Question 2: must be 0-fold and 4-fold sites?**
In my input data, I use the unfold SFS. I am confused about whether or not I should filter data again and use only 0-fold and 4-fold? 
Would be OK If I only use unfold data and ignore the Degeneracy of the genetic code?

**Question3: How to set the proportion of the sites in one region?**
In the tutorial "The length of the neutral (here, synonymous) and selected (here, non-synonymous) regions is typically calculated from the total length by using a proportionality principle where a proportion of the sites are deemed respectively synonymous and non-synonymous.  Does it means if a region length is 4k, so synonymous is 1k and non-syn is 3k? My study is about wheat, and I do not know how to set the proportion. 
**If I set 1:1, will it has a high impact on the DFE???**

**Question4:Which model is the best one? why alpha is so high?**
I run model A C Del with +r, and all models are significant and the result has a big difference, I am confused about which one is the best? Should different populations in different subgenomes use different models?
please check the attachment on my polyDFE model test.
[polyDFE_modelTest.pdf](https://github.com/paula-tataru/polyDFE/files/7497008/polyDFE_modelTest.pdf)

So sorry to ask you so many questions. I have appreciated it if you help me figure out these questions. 

Cheers,
Aoyue

**Comment by paula-tataru** [comment]
Hi Aoyue

**Question 1**
The bootstrap function has been made for SFS with just two regions, a neural one and one under selection, see comment [here](https://github.com/paula-tataru/polyDFE/blob/604fcd7db22e697a2d0a761f0ff41d57a0e2ea62/postprocessing.R#L1511)

In our experiments it seemed that modelling variably in mutation rate was not really necessary and unless you see an impact in the inference, I recommend you collapse your data to just two regions. Then there should be no issues with bootstrapping the data. See "Inference of mutation variability" in the [article](https://academic.oup.com/genetics/article/207/3/1103/5930676).

Otherwise, you can make 14 different files, bootstrap each one of them, and then merge the bootstraps back to create 14 regions for each bootstrap sample.

Bootstrapping can be used for calculating confidence intervals of your estimated parameters. This was done in the [article](https://academic.oup.com/genetics/article/207/3/1103/5930676) to obtain confidence intervals for the parameters estimated for the chimp data. See also "5.1 Bootstrap-based confidence intervals" in the tutorial

**Question 2**
Unless you want to perform some special analysis, I don't see any reason why you'd remove 0-fold and 4-fold degenerate sites.

**Question 3**
A proportion of 1:2 for neutral vs under selection (so if 3k sites, 1k are neutral and 2k are under selection) is the simplest way of calculating the region length when dealing with _coding regions_, but there are methods out there that perform more through calculations. It all depends on how you calculated your SFS - as noted in the tutorial, the software you used for that should typically also tell you the regions lengths.

I do not know how you generated your data, so I cannot say what it the correct answer - but most likely not 1:1. And yes, setting this incorrectly will _bias_ the results.

**Question 4**
For choosing the best model, see "5. Hypothesis testing" in the tutorial. You can use AIC to choose between different models (A vs C for example), you can use a LRT to use between nested models (A where s_max is set to 0 or can be freely estimated) or you can use model averaging.

**Comment by AoyueBi** [comment]
Hi Tataru,

You are so nice! I really thank you for your help! And I will test these again.
Cheers,

Aoyue

**Comment by AoyueBi** [comment]
Hi Tataru,

You are so nice! I really thank you for your help! And I will test these again.
Cheers,

Aoyue
