### ISSUE TITLE
1

### ISSUE THREAD

**Issue by BaHole** [paula-tataru/polyDFE#8]
Hi

**Comment by paula-tataru** [comment]
Hi,

The length of the sequence is, as a starting point, the length of the region you use for calling the SNPs - so that is all up to you and how you do the data processing. This also means that you do not need to have the same length for the polymorphism and divergence region.  For example, for the chimp data used in our article and tutorial, SNPs were called only in specific regions that met certain criteria, and for divergence, this criteria had to be met in both species, leading to a divergence length that was slightly lower than the polymorphism length. See the the original article describing the data: https://academic.oup.com/gbe/article/7/4/1122/535617

Once you decide which regions you use for calling SNPs, the software that you use should also report the final length, calculated as the number of positions where SNP calling could be performed, as described in the tutorial.

Regarding the 3/4 that is a good starting point and would probably work most of the times. But I would imagine that different species might diverge more from this 3/4 rule. See a more correct method of counting sites here https://academic.oup.com/mbe/article/17/1/32/975527 (Counting Synonymous and Nonsynonymous Sites)

/Paula
